import { register } from "./src/services/authService.js";

const businesses = [
  {
    email: "barbearia1@email.com",
    password: "123456",
    name: "Barbearia Estilo",
    telephone: "11999999901",
    role: "business",
    extra: {
      cnpj: "11111111000101",
      description: "Cortes clássicos e modernos",
    },
    address: {
      street: "Rua A",
      number: "100",
      district: "Bairro A",
      city: "São Paulo",
      state: "SP",
      zip_code: "01001000",
      complement: "Sala 1",
    },
  },
  {
    email: "salao1@email.com",
    password: "123456",
    name: "Salão Beleza Pura",
    telephone: "11999999902",
    role: "business",
    extra: { cnpj: "22222222000102", description: "Manicure e estética" },
    address: {
      street: "Rua B",
      number: "200",
      district: "Bairro B",
      city: "São Paulo",
      state: "SP",
      zip_code: "02002000",
      complement: "2º andar",
    },
  },
  {
    email: "barbearia2@email.com",
    password: "123456",
    name: "Barbearia Vip",
    telephone: "11999999903",
    role: "business",
    extra: { cnpj: "33333333000103", description: "Barbearia premium" },
    address: {
      street: "Rua C",
      number: "300",
      district: "Bairro C",
      city: "São Paulo",
      state: "SP",
      zip_code: "03003000",
      complement: null,
    },
  },
  {
    email: "salao2@email.com",
    password: "123456",
    name: "Salão Glamour",
    telephone: "11999999904",
    role: "business",
    extra: {
      cnpj: "44444444000104",
      description: "Cortes, coloração e estética",
    },
    address: {
      street: "Rua D",
      number: "400",
      district: "Bairro D",
      city: "São Paulo",
      state: "SP",
      zip_code: "04004000",
      complement: "Fundos",
    },
  },
  {
    email: "barbearia3@email.com",
    password: "123456",
    name: "Barbearia do Zé",
    telephone: "11999999905",
    role: "business",
    extra: {
      cnpj: "55555555000105",
      description: "Cortes rápidos e atendimento VIP",
    },
    address: {
      street: "Rua E",
      number: "500",
      district: "Bairro E",
      city: "São Paulo",
      state: "SP",
      zip_code: "05005000",
      complement: null,
    },
  },
  {
    email: "salao3@email.com",
    password: "123456",
    name: "Salão Top Hair",
    telephone: "11999999906",
    role: "business",
    extra: { cnpj: "66666666000106", description: "Especialista em penteados" },
    address: {
      street: "Rua F",
      number: "600",
      district: "Bairro F",
      city: "São Paulo",
      state: "SP",
      zip_code: "06006000",
      complement: "Próximo à praça",
    },
  },
  {
    email: "barbearia4@email.com",
    password: "123456",
    name: "Barbearia Premium",
    telephone: "11999999907",
    role: "business",
    extra: { cnpj: "77777777000107", description: "Serviços de luxo" },
    address: {
      street: "Rua G",
      number: "700",
      district: "Bairro G",
      city: "São Paulo",
      state: "SP",
      zip_code: "07007000",
      complement: null,
    },
  },
  {
    email: "salao4@email.com",
    password: "123456",
    name: "Salão Estilo Mulher",
    telephone: "11999999908",
    role: "business",
    extra: {
      cnpj: "88888888000108",
      description: "Estética feminina completa",
    },
    address: {
      street: "Rua H",
      number: "800",
      district: "Bairro H",
      city: "São Paulo",
      state: "SP",
      zip_code: "08008000",
      complement: "Loja 2",
    },
  },
  {
    email: "barbearia5@email.com",
    password: "123456",
    name: "Barbearia Moderna",
    telephone: "11999999909",
    role: "business",
    extra: { cnpj: "99999999000109", description: "Atendimento rápido" },
    address: {
      street: "Rua I",
      number: "900",
      district: "Bairro I",
      city: "São Paulo",
      state: "SP",
      zip_code: "09009000",
      complement: null,
    },
  },
  {
    email: "salao5@email.com",
    password: "123456",
    name: "Salão Divas",
    telephone: "11999999910",
    role: "business",
    extra: {
      cnpj: "10101010000110",
      description: "Cortes e estética avançada",
    },
    address: {
      street: "Rua J",
      number: "1000",
      district: "Bairro J",
      city: "São Paulo",
      state: "SP",
      zip_code: "10010000",
      complement: "3º andar",
    },
  },
];

const customers = [
  {
    email: "cliente1@email.com",
    password: "123456",
    name: "Maria Silva",
    telephone: "11988888801",
    role: "customer",
    extra: { cpf: "12345678901" },
    address: {
      street: "Rua X",
      number: "10",
      district: "Bairro X",
      city: "São Paulo",
      state: "SP",
      zip_code: "03003000",
      complement: "Apto 101",
    },
  },
  {
    email: "cliente2@email.com",
    password: "123456",
    name: "João Souza",
    telephone: "11988888802",
    role: "customer",
    extra: { cpf: "98765432100" },
    address: {
      street: "Rua Y",
      number: "20",
      district: "Bairro Y",
      city: "São Paulo",
      state: "SP",
      zip_code: "04004000",
      complement: null,
    },
  },
  {
    email: "cliente3@email.com",
    password: "123456",
    name: "Ana Oliveira",
    telephone: "11988888803",
    role: "customer",
    extra: { cpf: "11122233344" },
    address: {
      street: "Rua Z",
      number: "30",
      district: "Bairro Z",
      city: "São Paulo",
      state: "SP",
      zip_code: "05005000",
      complement: "Bloco B",
    },
  },
  {
    email: "cliente4@email.com",
    password: "123456",
    name: "Carlos Pereira",
    telephone: "11988888804",
    role: "customer",
    extra: { cpf: "55566677788" },
    address: {
      street: "Rua K",
      number: "40",
      district: "Bairro K",
      city: "São Paulo",
      state: "SP",
      zip_code: "06006000",
      complement: null,
    },
  },
  {
    email: "cliente5@email.com",
    password: "123456",
    name: "Juliana Santos",
    telephone: "11988888805",
    role: "customer",
    extra: { cpf: "99988877766" },
    address: {
      street: "Rua L",
      number: "50",
      district: "Bairro L",
      city: "São Paulo",
      state: "SP",
      zip_code: "07007000",
      complement: "Casa",
    },
  },
  {
    email: "cliente6@email.com",
    password: "123456",
    name: "Pedro Costa",
    telephone: "11988888806",
    role: "customer",
    extra: { cpf: "11223344556" },
    address: {
      street: "Rua M",
      number: "60",
      district: "Bairro M",
      city: "São Paulo",
      state: "SP",
      zip_code: "08008000",
      complement: null,
    },
  },
  {
    email: "cliente7@email.com",
    password: "123456",
    name: "Fernanda Lima",
    telephone: "11988888807",
    role: "customer",
    extra: { cpf: "22334455667" },
    address: {
      street: "Rua N",
      number: "70",
      district: "Bairro N",
      city: "São Paulo",
      state: "SP",
      zip_code: "09009000",
      complement: "Apto 202",
    },
  },
  {
    email: "cliente8@email.com",
    password: "123456",
    name: "Ricardo Almeida",
    telephone: "11988888808",
    role: "customer",
    extra: { cpf: "33445566778" },
    address: {
      street: "Rua O",
      number: "80",
      district: "Bairro O",
      city: "São Paulo",
      state: "SP",
      zip_code: "10010000",
      complement: null,
    },
  },
  {
    email: "cliente9@email.com",
    password: "123456",
    name: "Patrícia Gomes",
    telephone: "11988888809",
    role: "customer",
    extra: { cpf: "44556677889" },
    address: {
      street: "Rua P",
      number: "90",
      district: "Bairro P",
      city: "São Paulo",
      state: "SP",
      zip_code: "11011000",
      complement: "Casa",
    },
  },
  {
    email: "cliente10@email.com",
    password: "123456",
    name: "André Barbosa",
    telephone: "11988888810",
    role: "customer",
    extra: { cpf: "55667788990" },
    address: {
      street: "Rua Q",
      number: "100",
      district: "Bairro Q",
      city: "São Paulo",
      state: "SP",
      zip_code: "12012000",
      complement: null,
    },
  },
];

async function seed() {
  try {
    console.log("Inserindo negócios...");
    for (const business of businesses) {
      await register(business);
    }

    console.log("Inserindo clientes...");
    for (const customer of customers) {
      await register(customer);
    }

    console.log("Seed finalizado!");
  } catch (error) {
    console.error("Erro ao popular o banco:", error);
  }
}

seed();
